### ISSUE TITLE
Add support for broadcom (raspberry pi)

### ISSUE THREAD

**Issue by rsbohn** [adafruit/Adafruit_CircuitPython_BitmapSaver#20]
The broadcom port display is a FramebufferDisplay.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_bitmapsaver.py", line 127, in save_pixels
ValueError: Second argument must be a Bitmap or Display
```

If I disable that check I get this:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_bitmapsaver.py", line 94, in _write_pixels
ValueError: Display must have a 16 bit colourspace.
```

The broadcom display uses a 32 bit colourspace.

**Comment by tannewt** [comment]
I think this will take additions to CircuitPython as well. It may be more expedient to use an HDMI capture dongle to capture the screen.
